"""Configurações do projeto."""
from .configuracoes import (
    LARGURA_TELA, ALTURA_TELA, FPS, TITULO_JANELA,
    LINHA_CHAO, GRAVIDADE, FORCA_PULO, QUEDA_AGACHADO,
    VELOCIDADE_BASE_JOGO, INCREMENTO_VELOCIDADE,
    PONTOS_PARA_ACELERAR, TEMPO_RECARGA_ESPECIAL,
    VELOCIDADE_PROJETIL, ALTURAS_PTERO,
    BRANCO, PRETO, VERDE, VERMELHO, AZUL, AMARELO,
    CINZA_ESCURO, CINZA_CLARO,
    BASE_DIR, ASSETS_DIR, ARQUIVO_SAVE,
    DINO_VARIANTS, PROJETIL_IMAGE, CACTO_IMAGE, PTERO_IMAGE,
    LOJA_PRECOS_DINOS, LOJA_ITENS_CONSUMIVEIS,
    DADOS_JOGADOR_PADRAO,
    carregar_sprite, limpar_cache_imagens
)

__all__ = [
    'LARGURA_TELA', 'ALTURA_TELA', 'FPS', 'TITULO_JANELA',
    'LINHA_CHAO', 'GRAVIDADE', 'FORCA_PULO', 'QUEDA_AGACHADO',
    'VELOCIDADE_BASE_JOGO', 'INCREMENTO_VELOCIDADE',
    'PONTOS_PARA_ACELERAR', 'TEMPO_RECARGA_ESPECIAL',
    'VELOCIDADE_PROJETIL', 'ALTURAS_PTERO',
    'BRANCO', 'PRETO', 'VERDE', 'VERMELHO', 'AZUL', 'AMARELO',
    'CINZA_ESCURO', 'CINZA_CLARO',
    'BASE_DIR', 'ASSETS_DIR', 'ARQUIVO_SAVE',
    'DINO_VARIANTS', 'PROJETIL_IMAGE', 'CACTO_IMAGE', 'PTERO_IMAGE',
    'LOJA_PRECOS_DINOS', 'LOJA_ITENS_CONSUMIVEIS',
    'DADOS_JOGADOR_PADRAO',
    'carregar_sprite', 'limpar_cache_imagens'
]
